replicaCount: 1
createNamespace: true
existingConfigSecret: proxmox-csi-plugin
# Define the storage classes
storageClass:
  - name: proxmox-xfs
    storage: local-cluster-zfs
    reclaimPolicy: Delete
    fstype: xfs
    ssd: true
    # Define the storage class as default
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    mountOptions:
    - noatime
  - name: proxmox-retained-xfs
    storage: local-cluster-zfs
    reclaimPolicy: Retain
    fstype: xfs
    ssd: true
    mountOptions:
    - noatime
  - name: proxmox-ext4
    storage: local-cluster-zfs
    reclaimPolicy: Delete
    fstype: ext4
    cache: writethrough
    ssd: true
    mountOptions:
    - noatime
  - name: proxmox-retained-ext4
    storage: local-cluster-zfs
    reclaimPolicy: Retain
    fstype: ext4
    cache: writethrough
    ssd: true
    mountOptions:
    - noatime