# For single node clusters you may want to disable daemonSet and use replicaCount instead to have more than one instance running.
daemonSet:
  enabled: true
# replicaCount: 2

enabledControllers:
  - node-csr-approval
  - cloud-node
  # Only CSR Approval and cloud-node enabled.
  # - cloud-node-lifecycle  # Only useful for GKE
  # - node-ipam-controller  # Handled by cilium